### ISSUE TITLE
sqlite3.OperationalError: no such table: RKFace

### ISSUE THREAD

**Issue by iwoj** [RhetTbull/osxphotos#102]
I installed osxphotos via git.

`osxphotos query --keyword Happy --json ~/Pictures/Photos\ Library.photoslibrary
WARNING: Only tested on database versions [6000, 4025, 4016, 3301, 2622] You have database version=5001 which has not been tested
Traceback (most recent call last):
  File "/Users/ian/opt/anaconda3/bin/osxphotos", line 11, in <module>
    load_entry_point('osxphotos==0.27.4', 'console_scripts', 'osxphotos')()
  File "/Users/ian/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ian/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/ian/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ian/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ian/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/ian/opt/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/ian/opt/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/ian/opt/anaconda3/lib/python3.7/site-packages/osxphotos-0.27.4-py3.7.egg/osxphotos/__main__.py", line 840, in query
    no_place=no_place,
  File "/Users/ian/opt/anaconda3/lib/python3.7/site-packages/osxphotos-0.27.4-py3.7.egg/osxphotos/__main__.py", line 1339, in _query
    photosdb = osxphotos.PhotosDB(dbfile=db)
  File "/Users/ian/opt/anaconda3/lib/python3.7/site-packages/osxphotos-0.27.4-py3.7.egg/osxphotos/photosdb.py", line 262, in __init__
    self._process_database4()
  File "/Users/ian/opt/anaconda3/lib/python3.7/site-packages/osxphotos-0.27.4-py3.7.egg/osxphotos/photosdb.py", line 521, in _process_database4
    + "RKVersion.filename not like '%.pdf' and RKVersion.isInTrash = 0"
sqlite3.OperationalError: no such table: RKFace`

**Comment by RhetTbull** [comment]
@iwoj  Which version of MacOS are you running?  I'm guessing El Capitan from the error string below. If so, osxphotos does not support this version.  osxphotos has been tested on MacOS 10.12 - 10.15.4 

`WARNING: Only tested on database versions [6000, 4025, 4016, 3301, 2622] You have database version=5001 which has not been tested`

**Comment by RhetTbull** [comment]
Also, what is the version that Photos says when you click Photos | About Photos?

**Comment by iwoj** [comment]
I'm on OSX 10.15.4 and Photos Version 5.0 (141.19.150)

**Comment by RhetTbull** [comment]
Interesting--On my machine also with OSX 10.15.4 and Photos Version 5.0 (141.19.150) libraryVersion = "6000" whereas the error you posted indicates a libraryVersion of "5001" which I've never seen in any configuration.  If your willing to send me a copy of your database it would be helpful for debugging.  Easiest way is to use something like [Firefox Send](https://send.firefox.com/) to email to me at rturnbull+git@gmail.com  The files that would be helpful are photos.db and Photos.sqlite, both in `~/Pictures/Photos Library.photoslibrary/database`  photos.db has only metadata information about the library itself (e.g. which version of Photos) and should be very small <100KB.  Photos.sqlite contains the details of your library (photo names, keywords, etc) and could be hundreds of MB in size.  

Also, I've pushed an update to github to see if libraryVersion 5001 which you're reporting can be processed.  Try a `git pull` and see if you still get an error.

**Comment by RhetTbull** [comment]
@iwoj Are you still having this issue or does latest version of osxphotos process your database correctly?

**Comment by RhetTbull** [comment]
@iwoj if you're still using osxphotos I'd like to get some data on the version "5001" database.  In particular, the output of these two commands would be very helpful.  

`sqlite3 ~/Pictures/Photos\ Library.photoslibrary/database/photos.db ".schema" > db_schema.txt`

`sqlite3 ~/Pictures/Photos\ Library.photoslibrary/database/photos.sqlite ".schema" > sqlite_schema.txt`

In the commands above, replace ~/Pictures/Photos\ Library.photoslibrary/ with the path to the library that's causing the error.

**Comment by RhetTbull** [comment]
I think this is fixed in [v0.44.8](https://github.com/RhetTbull/osxphotos/releases/tag/v0.44.8)
