### ISSUE TITLE
Installation Issue with bpylist2-2.0.3

### ISSUE THREAD

**Issue by bkovacev** [RhetTbull/osxphotos#112]
Hi I can't seem to install either through `pip install` or through `python setup.py install`.

Python: 3.6
OSX: 10.15.4
using venv

```
Traceback (most recent call last):
  File "setup.py", line 74, in <module>
    include_package_data=True,
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/__init__.py", line 145, in setup
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/command/install.py", line 67, in run
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/command/install.py", line 117, in do_egg_install
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/command/easy_install.py", line 418, in run
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/command/easy_install.py", line 660, in easy_install
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/command/easy_install.py", line 707, in install_item
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/command/easy_install.py", line 752, in process_distribution
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/pkg_resources/__init__.py", line 782, in resolve
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/pkg_resources/__init__.py", line 1065, in best_match
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/pkg_resources/__init__.py", line 1077, in obtain
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/command/easy_install.py", line 679, in easy_install
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/command/easy_install.py", line 705, in install_item
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/command/easy_install.py", line 890, in install_eggs
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/command/easy_install.py", line 1158, in build_and_install
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/command/easy_install.py", line 1144, in run_setup
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/sandbox.py", line 253, in run_setup
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/sandbox.py", line 195, in setup_context
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/sandbox.py", line 166, in save_modules
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/sandbox.py", line 141, in resume
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/_vendor/six.py", line 685, in reraise
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/sandbox.py", line 154, in save_modules
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/sandbox.py", line 195, in setup_context
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/sandbox.py", line 250, in run_setup
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/sandbox.py", line 45, in _execfile
  File "/var/folders/gm/jjd0y8xn7z1g__4gnpwhg1c40000gn/T/easy_install-nsvplvt4/bpylist2-2.0.3/setup.py", line 51, in <module>
    project_urls={"GitHub": "https://github.com/RhetTbull/osxphotos"},
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/__init__.py", line 144, in setup
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/__init__.py", line 139, in _install_setup_requires
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/setuptools/dist.py", line 724, in fetch_build_eggs
  File "/Users/bkovacev/PycharmProjects/photoOrganizer/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/pkg_resources/__init__.py", line 791, in resolve
setuptools.sandbox.UnpickleableException: ContextualVersionConflict(pycodestyle 2.3.1 (/private/var/folders/gm/jjd0y8xn7z1g__4gnpwhg1c40000gn/T/easy_install-nsvplvt4/bpylist2-2.0.3/.eggs/pycodestyle-2.3.1-py3.6.egg), Requirement.parse('pycodestyle<2.6.0,>=2.5.0'), {'flake8'})
```

**Comment by RhetTbull** [comment]
For python < 3.8, I had to make a custom version of bpylist2 to get around this error.  Try:
`pip install -r requirements.txt` which will pull the right version of bpylist2 from my github then try `python3 setup.py install` again.  I'll update the docs to reflect this.

**Comment by bkovacev** [comment]
That worked perfectly, thank you so much for the prompt reply @RhetTbull . Closing this.
