### ISSUE TITLE
KeyError in _build_album_folder_hierarchy_4

### ISSUE THREAD

**Issue by adamshand** [RhetTbull/osxphotos#116]
Hi Rhet,

Many thanks for adding the album and people keywording feature.  My photos album finished downloading overnight and I gave osxphotos a try this morning.  I assume I'm doing something dumb but everything I've tried resets in a KeyError.

```
hebe(adam)$ osxphotos  albums /tmp/iphoto/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/osxphotos", line 10, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/osxphotos/__main__.py", line 429, in albums
    photosdb = osxphotos.PhotosDB(dbfile=db)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/osxphotos/photosdb.py", line 279, in __init__
    self._process_database4()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/osxphotos/photosdb.py", line 666, in _process_database4
    folder_hierarchy = self._build_album_folder_hierarchy_4(parent_folder)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/osxphotos/photosdb.py", line 1226, in _build_album_folder_hierarchy_4
    parent_uuid = self._dbfolder_details[uuid]["parentFolderUuid"]
KeyError: 'ViVs7qlgSMiErMZ2kctSCg'
```

This is on 10.14.6 with my photo library on an external HFS formatted drive.

I've tried using a few different versions of osxphotos and both installing from source and using the downloadable executable.  All give a similar error:

```
hebe(adam)$ ~/Downloads/osxphotos-0.28.8 export /tmp/iphoto/ --directory "{album}" --album-keyword --exiftool --sidecar xmp
Using last opened Photos library: /Volumes/ADAM.1T/Photos Library.photoslibrary
Traceback (most recent call last):
  File "cli.py", line 19, in <module>
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "site-packages/click/decorators.py", line 27, in new_func
  File "site-packages/click/decorators.py", line 17, in new_func
  File "osxphotos/__main__.py", line 1105, in export
  File "osxphotos/__main__.py", line 1396, in _query
  File "osxphotos/photosdb.py", line 279, in __init__
  File "osxphotos/photosdb.py", line 666, in _process_database4
  File "osxphotos/photosdb.py", line 1226, in _build_album_folder_hierarchy_4
KeyError: 'ViVs7qlgSMiErMZ2kctSCg'
[6138] Failed to execute script cli
```

Happy to provide any details that are useful.

Best wishes from New Zealand,
Adam.

**Comment by RhetTbull** [comment]
@adamshand ugh...definitely a bug.  Thanks for opening an issue.  I'll take a look.  If you don't mind sharing a copy of your database file it would be very useful for debugging.  The file should be in ~/Pictures/Photos Library.photoslibrary/database/photos.db.  The file contains metadata about the photos including names, locations, etc. but no actual images.  Easiest way is probably to zip it and send via something like [Firefox Send](https://send.firefox.com/) to rturnbull+git@gmail.com If you can't share the database I can add some debugging code and have you run with debugging enabled.

**Comment by adamshand** [comment]
Uploading now.  Will email you the link.

**Comment by RhetTbull** [comment]
I think I found the bug (wasn't filtering out "special" album types) -- try 0.28.10 and let me know if it works.

**Comment by adamshand** [comment]
Seems to be working, woohoo!  DIdn't expect to see all my old iPhoto events in there.  That's cool.

```
hebe(adam)$ ~/Downloads/osxphotos-0.28.10 --db /Volumes/ADAM.1T/Photos\ Library.photoslibrary/  export /tmp/photos --album Bike
Exporting 8 photos to /tmp/photos...
  [####################################]  100%
```

**Comment by adamshand** [comment]
Yep this looks like it's working.  Thank you so much, this is epic.

The only thing I wish it did differently was include folders in the album name.  At the moment if I have a photo album called "Bike" in a folder called "Projects" what comes through in the take is just "Bike".  It would be ideal if it came through as "Projects/Bike".  Easy enough to work around by renaming albums before exporting.

Thanks for the example command line, it would have taken me a while to figure out that I needed "--exiftool --sidecar xmp" in order to get the the tags into the pictures.

Unfortunately something about the way the tags are written causes Shotwell under Linux to crash (screenshot attached in case it means anything to you).  

![Screenshot from 2020-04-29 14-31-55](https://user-images.githubusercontent.com/130651/80556229-0b875e80-8a27-11ea-9f42-bf0e7db08340.png)

When I look at the metadata with ImageMagick I see an "unknown" line, I wonder if that's what is causing problems?  Fortunately digiKam seems to be fine with it, so not a huge deal for me.

```
    Profile-iptc: 47 bytes
      Keyword[2,25]: Wanganui
      unknown[2,0]: 
      Keyword[2,25]: Tink Printing
      Keyword[2,25]: Weta
```

Thanks again.

**Comment by adamshand** [comment]
Hrm, just blew away the cache and db for Shotwell and tried again and it seems to be working fine now.

**Comment by RhetTbull** [comment]
Glad it's working!  You can get folder name/album with “{folder_album}” as the --directory template 

--exiftool writes the metadata to photos with exiftool

--sidecar xmp writes the XMP file some apps like lightroom use to import metadata. If you're using exiftool you probably don't need this, it's just provided for completeness or for those that don't want to modify the exif in the photos. 

I'm not familiar with shotwell and indeed have done little testing with the exported metadata -- it's possible there's something amiss in the metadata. Do you know if the error was reading exif data or the XMP?  If you run into other issues with metadata open an issue and I'll look into it.

**Comment by adamshand** [comment]
That's useful thanks.  Probably won't bother with the sidecar then, it can always be regenerated if need be if the data is in the actual files.

What I was meaning is for the folder name is for it to be part of the metadata (as opposed to the exported folder structure).  Because I've got photos going back to the 1990s I organised my Photos.app albums like:

```
1990s
  - 1990
    - Favourites
    - Event7
    …
  - 1991
  …
2000s
  - 2000
    - Favourites
    …
  - 2001
```

In my case the folders are essentially part of the album name and with them albums names can be ambiguous.

Easy enough to rename my albums to make sure that everything exports in a way that's useful to me, but I wonder if using "folder/album" as the album tag would be better for people?

**Comment by RhetTbull** [comment]
That's reasonable -- I could add a flag to treat folder as keyword.  In your example would you want separate keywords for 1990s, 1990, Event7 or a single keyword like 1990s_1990_Event7? (eg whole path)

**Comment by adamshand** [comment]
I'd prefer them as a single keyword (eg. "1990s/1996/Favourites") because I'm using the names to build an album folder structure similar to what I had in Photos.app.

**Comment by RhetTbull** [comment]
OK -- that seems reasonable. If / is valid in a tag and your software will read those then definitely makes sense to include the "/".  I opened issue #117 to track this. Should be a fairly easy fix.
