### ISSUE TITLE
Stopped working | osxphotos --version exception key error 'styles' | really weird

### ISSUE THREAD

**Issue by oPromessa** [RhetTbull/osxphotos#1393]
**Before submitting a bug report, please ensure you are running the most recent version of osxphotos and that the bug is reproducible on the latest version**

- If you installed with pip: `pip install --upgrade osxphotos` => ok

**Describe the bug**
Out of the blue a simple `osxphotos --version` or solely `osxphotos` command gives the following errors.

I have two venv environments for python 3.9 and 3.11 and the same happens!

Did not upgrade/update any of the pythons. They are installed with brew.

Just earlier the nigh export ran smoothly!

Tried
* Mac restart. Same error!
* uninstall with pip osxphotos and install
* python check indicates no issues!
* still to try to create a new venv
* still to try some update of python with brew? but it seems there is not!

```
$  osxphotos 
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.18/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: 'styles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/MSP/Documents/Apps/osxphotos/venv/bin/osxphotos", line 5, in <module>
    from osxphotos.__main__ import cli_main
  File "/Users/MSP/Documents/Apps/osxphotos/venv/lib/python3.9/site-packages/osxphotos/__main__.py", line 3, in <module>
    from .cli.cli import cli_main
  File "/Users/MSP/Documents/Apps/osxphotos/venv/lib/python3.9/site-packages/osxphotos/cli/__init__.py", line 49, in <module>
    from .cli import cli_main
  File "/Users/MSP/Documents/Apps/osxphotos/venv/lib/python3.9/site-packages/osxphotos/cli/cli.py", line 21, in <module>
    from .exiftool_cli import exiftool
  File "/Users/MSP/Documents/Apps/osxphotos/venv/lib/python3.9/site-packages/osxphotos/cli/exiftool_cli.py", line 26, in <module>
    from .export import export, render_and_validate_report
  File "/Users/MSP/Documents/Apps/osxphotos/venv/lib/python3.9/site-packages/osxphotos/cli/export.py", line 97, in <module>
    from .cli_commands import logger
  File "/Users/MSP/Documents/Apps/osxphotos/venv/lib/python3.9/site-packages/osxphotos/cli/cli_commands.py", line 37, in <module>
    set_rich_theme(get_theme())
  File "/Users/MSP/Documents/Apps/osxphotos/venv/lib/python3.9/site-packages/osxphotos/cli/color_themes.py", line 191, in get_theme
    return get_default_theme()
  File "/Users/MSP/Documents/Apps/osxphotos/venv/lib/python3.9/site-packages/osxphotos/cli/color_themes.py", line 205, in get_default_theme
    theme_manager = get_theme_manager()
  File "/Users/MSP/Documents/Apps/osxphotos/venv/lib/python3.9/site-packages/osxphotos/cli/color_themes.py", line 180, in get_theme_manager
    return ThemeManager(
  File "/Users/MSP/Documents/Apps/osxphotos/venv/lib/python3.9/site-packages/rich_theme_manager/manager.py", line 52, in __init__
    self.load_themes(update=update)
  File "/Users/MSP/Documents/Apps/osxphotos/venv/lib/python3.9/site-packages/rich_theme_manager/manager.py", line 91, in load_themes
    theme = Theme.read(str(path))
  File "/Users/MSP/Documents/Apps/osxphotos/venv/lib/python3.9/site-packages/rich_theme_manager/theme.py", line 316, in read
    return cls.from_file(config_file, source=path, inherit=inherit)
  File "/Users/MSP/Documents/Apps/osxphotos/venv/lib/python3.9/site-packages/rich_theme_manager/theme.py", line 289, in from_file
    name: Style.parse(value) for name, value in config.items("styles")
  File "/usr/local/Cellar/python@3.9/3.9.18/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 849, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'styles'
(venv) 
$ sw_vers 
ProductName:	macOS
ProductVersion:	12.7.2
BuildVersion:	21G1974
```

**To Reproduce**
1. What' the full command line you used with osxphotos?
osxphotos --version
3. What was the error output?
See above.

**Expected behavior**
The regular operation of osxphotos! That has been operating for months/years now!!!

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Mac Monterey 12.7.2
 - osxphotos version (`osxphotos --version`): 0.67.3
 - It happens with both python 3.9.18 and 3.11.5 (installed with brew)

**Additional context**
Last upgrade done to the Mac to 12.7.2 was done weeks ago!
Last upgrade osxphotos to 0.67.3 was also done weeks ago!

**Comment by RhetTbull** [comment]
Try `pipx reinstall-all`

**Comment by RhetTbull** [comment]
My guess is this is something homebrew did to break the venv.  I'd first start with a `pipx reinstall-all`. If that doesn't work, check in`~/.config/osxphotos/themes` and see if there are theme files there.  `cat dark.theme` and verify there's a `[styles]` section:

Should look something like this:

```ini
[metadata]
name = dark
description = Dark mode theme
tags = dark
inherit = True

[styles]
bar.back = rgb(68,71,90)
bar.complete = rgb(249,38,114)
bar.finished = rgb(80,250,123)
bar.pulse = rgb(98,114,164)
change = bold bright_red
color = rgb(248,248,242)
count = rgb(139,233,253)
```

**Comment by oPromessa** [comment]
Yup... you's right. the dark.theme file is empty :(

```sh
$ ls -l ~/.config/osxphotos/themes/
total 24
25947953 0 drwxr-xr-x  6 MSP  staff   192B May  2  2022 .
25264515 0 drwxr-xr-x  3 MSP  staff    96B Aug  7  2022 ..
25947954 0 -rw-r--r--  1 MSP  staff     0B Jan 20 12:34 dark.theme
25947955 8 -rw-r--r--  1 MSP  staff   621B Jan 20 12:34 light.theme
25947956 8 -rw-r--r--  1 MSP  staff   465B Jan 20 12:34 mono.theme
25947957 8 -rw-r--r--  1 MSP  staff   437B Jan 20 12:34 plain.theme
(venv.new) 
```

* Reason why is probably affecting all installs/venvs.
* I don't use pipx. With pip tried `pip install  --force-reinstall --no-cache-dir osxphotos` but same issue.
* Created a new python 3.11 venv, installed **pipx** and then osxphotos... but same result...as expected I guess.
* If I try to use another theme it still gives the error as dark.theme is 0 in size.
* Recreated dark.theme with your input above and voilá ... it works.

Will go thru TimeMachine backups to see when dark.theme was screwed up!

Reinstall does not seem to re-create/cleanup the themes folder.

Life saver! Thanks so much for the quick support/response!

**Comment by oPromessa** [comment]
I can see from TM between 12:34 and 12:43 today the file became empty.
Looking at older backups it seems these files are updated each time osxphotos runs.
What I was doing at the time was going over the updated pics in the last run to check their history.

```sh
FOLDER=~/Pictures/Pictures/Logs
echo $FOLDER
osxphotos exportdb ${FOLDER}/.osxphotos_export.db --report ${FOLDER}/report.csv 0
mlr --icsv --ocsv filter '$exported == 1 && $updated == 1' then cut -f filename ${FOLDER}/report.csv | sed 's%/Volumes/photo/Family.Photos/%%' | tail +2 |  ( cd ${FOLDER} ; xargs -L1 -IX sh -c 'echo "X"; osxphotos exportdb .osxphotos_export.db --history "X"' )
```

All is good now!

**Comment by RhetTbull** [comment]
> And I did a few Ctrl-C to cancel... maybe in one of the Ctrl-C it garbled the theme file. Don't know!

That's probably what happened but osxphotos should be more robust in reading the themes.  I'll add an issue to catch errors opening the themes and use default theme if it can't be read.
