### ISSUE TITLE
problem with folder_names when using templates

### ISSUE THREAD

**Issue by grundsch** [RhetTbull/osxphotos#148]
Hi,
I have a strange bug. When using directory templates, the export crashes with an error about folder_names, although I'm not using folder_names in the template:

```
osxphotos export -V --update --directory '{created.year}/{created.mm}-{created.month}/{created.dd}-{created.dow}' --from-date 2020-05-17 /Volumes/Multimedia/Photos/photos_backup/LIBRARY
Using last opened Photos library: /Users/grundsch/Pictures/Photos Library.photoslibrary
Exporting 11 photos to /Volumes/Multimedia/Photos/photos_backup/LIBRARY...
Exporting 13A26AC0-AD64-45F5-BCBF-38BEB273968A.mov as IMG_4583.MOV
Skipped up to date file /Volumes/Multimedia/Photos/photos_backup/LIBRARY/2020/05-May/23-Saturday/IMG_4583.MOV
Exporting 4B7675E3-30FB-4BB3-B399-1518DC822BED.mov as IMG_4584.MOV
Skipped up to date file /Volumes/Multimedia/Photos/photos_backup/LIBRARY/2020/05-May/23-Saturday/IMG_4584.MOV
Skipping missing edited photo for IMG_4584.MOV
Exporting 4B6BFBFC-F51B-45D7-8266-C979F9F54A28.jpeg as 1552BFFC-1918-48CD-B1D5-C79C63F3AB88.JPG
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/osxphotos-0.29.3-py3.7.egg/osxphotos/albuminfo.py", line 63, in folder_names
    return self._folder_names
AttributeError: 'AlbumInfo' object has no attribute '_folder_names'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/osxphotos", line 11, in <module>
    load_entry_point('osxphotos==0.29.3', 'console_scripts', 'osxphotos')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/osxphotos-0.29.3-py3.7.egg/osxphotos/__main__.py", line 1320, in export
    export_db,
  File "/usr/local/lib/python3.7/site-packages/osxphotos-0.29.3-py3.7.egg/osxphotos/__main__.py", line 1799, in export_photo
    dirnames, unmatched = photo.render_template(directory)
  File "/usr/local/lib/python3.7/site-packages/osxphotos-0.29.3-py3.7.egg/osxphotos/photoinfo/photoinfo.py", line 741, in render_template
    if album.folder_names:
  File "/usr/local/lib/python3.7/site-packages/osxphotos-0.29.3-py3.7.egg/osxphotos/albuminfo.py", line 68, in folder_names
    self._folder_names = self._db._album_folder_hierarchy_list(self._uuid)
  File "/usr/local/lib/python3.7/site-packages/osxphotos-0.29.3-py3.7.egg/osxphotos/photosdb/photosdb.py", line 1944, in _album_folder_hierarchy_list
    return self._album_folder_hierarchy_list_5(album_uuid)
  File "/usr/local/lib/python3.7/site-packages/osxphotos-0.29.3-py3.7.egg/osxphotos/photosdb/photosdb.py", line 1986, in _album_folder_hierarchy_list_5
    folders = self._dbalbum_folders[album_uuid]
KeyError: '71926307-2574-4C2A-A1E1-1A91E6FBB6BD'
```

Any idea what is going on?
I'm using python 3.7.7 from brew, and installed the required packages as mentioned in the readme.

BR,
 Stéphane

**Comment by RhetTbull** [comment]
That is a most bizarre bug...there may be an underlying bug in an uncaught exception in `_album_folder_hierarchy_list_5` which builds the folder hierarchy list but I don't see how that code was possibly reached during execution!  I'll look into it today.

**Comment by RhetTbull** [comment]
@grundsch I pushed a fix that should catch this exception. There's possibly an underlying issue with the processing of the albums and folders but without a copy of the database that's causing the error I can't dig into it further.  Your issue did expose an inefficiency in the template process I'll work on (opened #149).  Try `git pull` and run again and let me know if you still have an issue with this.  

I'm happy to look into the root cause of possible bug in album processing but would need a copy of your database -- if you're interested in sharing let me know and I'll provide instructions on how to send it.

**Comment by grundsch** [comment]
well done, that did the trick!
If you still need the database, let me know.

**Comment by RhetTbull** [comment]
Great! @grundsch I'd like to understand why the code failed in the first place.  If you don't mind sharing the database, the files I need are ~/Pictures/Photos Library.photoslibrary/database/Photos.sqlite and ~/Pictures/Photos Library.photoslibrary/database/photos.db.  They're probably large so the easiest way to send them is to zip and send via something like [Firefox send](https://send.firefox.com/) to rturnbull+git@gmail.com  The database contains metadata about the photos but no actual photos.
