### ISSUE TITLE
Database locked, creating temporary copy, but fails

### ISSUE THREAD

**Issue by torarnv** [RhetTbull/osxphotos#1539]
After having tried `--download-missing` unsuccessfully from an ssh session with both AppleScript and PhotoKit, I then tried on the machine itself, and got:

```
Database locked, creating temporary copy.
Error copying/Users/torarne/Pictures/Photos Library.photoslibrary/database/photos.db to /var/folders/vp/j9r0pczs6_9_jq3wqnztmj9w0000gn/T/osxphotos_b6w27ele/photos.db
Something went wrong and osxphotos encountered an error:
```

**Comment by torarnv** [comment]
```
Error:
Traceback (most recent call last):
  File "/Users/torarne/dev/osxphotos/osxphotos/fileutil.py", line 308, in copy
    shutil.copy(str(src), str(dest))
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 419, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted: '/Users/torarne/Pictures/Photos Library.photoslibrary/database/photos.db'
```

**Comment by torarnv** [comment]
Worked after giving `iTerm` permission to access Photos in the system settings. Worth an explicit check in the code for this scenario with a user-friendly error message perhaps?

**Comment by RhetTbull** [comment]
> Worked after giving iTerm permission to access Photos in the system settings. Worth an explicit check in the code for this scenario with a user-friendly error message perhaps?

I'll look into this but iTerm should have popped up a dialog asking for permission. In macOS it's the responsibility of the calling app (in this case iTerm, not Python or osxphotos which cannot, as a command line tool, request the necessary permissions). I've had problems with iTerm in the past though -- they fixed it in nightly build but I don't know if it's fixed in the regular build.

**Comment by torarnv** [comment]
Ah, right. I had probably run some command prior to this that tried to access the photo library directory, and I had denied it. Perhaps `osxphotos` can stat or touch the library directory to somehow figure out if it has permissions to access it, before going down the code paths that then fail on assumptions about reading the actual library database?

**Comment by afeld** [comment]
I didn't get the permissions prompt running from the Visual Studio Code integrated terminal, resulting in a similar vague error. Tried reading the file myself, which revealed the error:

```
$ sqlite3 "/Users/afeld/Pictures/Photos Library.photoslibrary/database/Photos.sqlite"
Error: unable to open database "/Users/afeld/Pictures/Photos Library.photoslibrary/database/Photos.sqlite": authorization denied
```

I then ran `osxphotos export from OSX's built-in Terminal and got the permissions prompt, then it worked fine 🤷 This might be the issue: https://github.com/microsoft/vscode/issues/307364
