### ISSUE TITLE
OSXPhotos no longer works on Ubuntu linux

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#1604]
I first noticed this in the CI which stopped working a few weeks ago.  Installing OSXPhotos fails with:

`packaging.version.InvalidVersion: Invalid version: '6.5.0-27-generic'`

Other users have reported it not working on linux. The weird thing is that even old versions that used to work no longer work. For example, this should work but fails:

`pipx install osxphotos==0.66.0`

**Comment by RhetTbull** [comment]
Looks like [it's pip](https://stackoverflow.com/questions/75202383/raise-packaging-version-invalidversion-linux-pip)

**Comment by RhetTbull** [comment]
Work around:

```bash
python3 -m venv venv-osxphotos
source venv-osxphotos/bin/activate
python3 -m pip install osxphotos
```

**Comment by RhetTbull** [comment]
I've added the above instructions to the README. Beyond this, I don't think there's anything else osxphotos can do. The problem appears to be an issue between setuptools and some packages that are installed in the system linux python environment. As linux is not the primary use case for osxphotos, I think that having instructions in the README for using a venv is sufficient.

**Comment by mschering** [comment]
Unfortunately the workaround no longer seems to work. I have Ubuntu 24.10. I installed python3 and ran your commands:

`schering@mschering-UX430UAR:~$ python3 -m venv .venv-osxphotos
mschering@mschering-UX430UAR:~$ source .venv-osxphotos/bin/activate
(.venv-osxphotos) mschering@mschering-UX430UAR:~$ 
(.venv-osxphotos) mschering@mschering-UX430UAR:~$ python3 -m pip install osxphotos
Collecting osxphotos
  Downloading osxphotos-0.69.2-py3-none-any.whl.metadata (16 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 174, in __bool__
    return any(self)
           ^^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 53, in _iter_built
    candidate = func()
                ^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 186, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 232, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 303, in __init__
    super().__init__(
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 247, in _prepare
    self._check_metadata_consistency(dist)
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 229, in _check_metadata_consistency
    list(dist.iter_dependencies(list(dist.iter_provided_extras())))
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_dists.py", line 218, in iter_dependencies
    elif not extras and req.marker.evaluate({"extra": ""}):
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_vendor/packaging/markers.py", line 325, in evaluate
    return _evaluate_markers(self._markers, current_environment)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_vendor/packaging/markers.py", line 225, in _evaluate_markers
    groups[-1].append(_eval_op(lhs_value, op, rhs_value))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_vendor/packaging/markers.py", line 183, in _eval_op
    return spec.contains(lhs, prereleases=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_vendor/packaging/specifiers.py", line 552, in contains
    normalized_item = _coerce_version(item)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_vendor/packaging/specifiers.py", line 28, in _coerce_version
    version = Version(version)
              ^^^^^^^^^^^^^^^^
  File "/home/mschering/.venv-osxphotos/lib/python3.12/site-packages/pip/_vendor/packaging/version.py", line 202, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pip._vendor.packaging.version.InvalidVersion: Invalid version: '6.11.0-21-generic'
`

I hope this can be fixed somehow.

Best regards,
Merijn

**Comment by RhetTbull** [comment]
Try installing with uv. See instructions [here](https://github.com/RhetTbull/osxphotos?tab=readme-ov-file#installation-using-uv)

I've not tried this on Linux but it might work

**Comment by mschering** [comment]
Thanks, that worked.
