### ISSUE TITLE
Framework UniformTypeIdentifiers could not be found

### ISSUE THREAD

**Issue by drodner** [RhetTbull/osxphotos#1680]
When running the latest version of osxphotos, I get the following error:
ImportError: Framework UniformTypeIdentifiers could not be found

I tried doing the pipx upgrade osxphotos, but still get the issue. I also tried uninstall and reinstall but that did not solve it either. No parameters are necessary to cause the issue. Just type osxphotos. 

Version of MacOS is 10.15.7.  Full call stack is:

Lori@LoriMac ~ % osxphotos
Traceback (most recent call last):
  File "/Users/Lori/.local/bin/osxphotos", line 5, in <module>
    from osxphotos.__main__ import cli_main
  File "/Users/Lori/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/osxphotos/__main__.py", line 3, in <module>
    from .cli.cli import cli_main
  File "/Users/Lori/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/osxphotos/cli/__init__.py", line 48, in <module>
    from .albums import albums
  File "/Users/Lori/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/osxphotos/cli/albums.py", line 12, in <module>
    from .cli_params import DB_ARGUMENT, DB_OPTION, JSON_OPTION
  File "/Users/Lori/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/osxphotos/cli/cli_params.py", line 14, in <module>
    from .param_types import *
  File "/Users/Lori/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/osxphotos/cli/param_types.py", line 17, in <module>
    from osxphotos.export_db_utils import export_db_get_version
  File "/Users/Lori/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/osxphotos/export_db_utils.py", line 25, in <module>
    from .photo_signature import photo_signature
  File "/Users/Lori/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/osxphotos/photo_signature.py", line 10, in <module>
    from .photoinfo_file import PhotoInfoFromFile
  File "/Users/Lori/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/osxphotos/photoinfo_file.py", line 21, in <module>
    from .image_file_utils import is_image_file, is_video_file
  File "/Users/Lori/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/osxphotos/image_file_utils.py", line 19, in <module>
    import cgmetadata
  File "/Users/Lori/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/cgmetadata/__init__.py", line 4, in <module>
    from .classes import ImageMetadata, ImageMetaData, VideoMetadata, VideoMetaData
  File "/Users/Lori/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/cgmetadata/classes.py", line 6, in <module>
    from .cgmetadata import (
  File "/Users/Lori/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/cgmetadata/cgmetadata.py", line 28, in <module>
    from .xmp import is_xmp_packet, metadata_dictionary_from_xmp_packet
  File "/Users/Lori/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/cgmetadata/xmp.py", line 13, in <module>
    from .utils import single_quotes_to_double_quotes, strip_xmp_packet
  File "/Users/Lori/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/cgmetadata/utils.py", line 10, in <module>
    import UniformTypeIdentifiers
  File "/Users/Lori/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/UniformTypeIdentifiers/__init__.py", line 17, in <module>
    objc.pathForFramework(
  File "/Users/Lori/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/objc/_dyld.py", line 142, in pathForFramework
    fpath, name, version = infoForFramework(dyld_find(path))
                                            ^^^^^^^^^^^^^^^
  File "/Users/Lori/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/objc/_dyld.py", line 136, in dyld_find
    return dyld_framework(filename, framework_name, version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lori/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/objc/_dyld.py", line 102, in dyld_framework
    raise ImportError(f"Framework {framework_name} could not be found")
ImportError: Framework UniformTypeIdentifiers could not be found
Lori@LoriMac ~ %

**Comment by RhetTbull** [comment]
The UTI APIs changed on macOS 11 and [UniformTypeIdentifiers](https://developer.apple.com/documentation/uniformtypeidentifiers#) is only available on macOS 11+. Looks like the dependency [cgmetadata](https://github.com/RhetTbull/CGMetadata), which I also maintain, is the issue.  I have an old machine running 10.15.7 I can dig up and do some testing  to see if I can work around this. If not I may need to drop support for macOS 10.15.7.

**Comment by drodner** [comment]
OK. I appreciate you checking into that. If not, what's the most recent version that would work on 10.15.7? And is it possible using pipx to revert to that specific version? Thanks!

**Comment by RhetTbull** [comment]
I think 0.67.10 should work. You can use `pipx install osxphotos==0.67.10`

**Comment by RhetTbull** [comment]
I think this should be fixed in 0.68.6 but I've not been able to test it on 10.15 to verify.

**Comment by RhetTbull** [comment]
Thanks for the feedback. I'll take a look when I get a chance.

**Comment by RhetTbull** [comment]
I've created a new library, [utitools](https://github.com/RhetTbull/utitools) that implements the needed functionality across macOS versions and linux. I need to test this on 10.15 then I'll refactor osxphotos to use this which should resolve the issue.
