### ISSUE TITLE
ssl errors on macOS Sequoia install

### ISSUE THREAD

**Issue by Juggler00** [RhetTbull/osxphotos#1749]
M2 MacBook Air
macOS Sequoia 15.1.1

With your most recent release, I wanted to take another try at installing and using your tool. I followed the instructions to install uv, then installed osxphotos from the CLI. When I tried to run osxphotos (--help or --version) I get an ssl error (details below).

Install sequence:
```
Juggler@Jugglers-Air ~ % curl -LsSf https://astral.sh/uv/install.sh | sh
<<< restart terminal >>>
Juggler@Jugglers-MacBook-Air ~ % uv tool install osxphotos
```
I then rebooted the computer.

Error output:
```
Juggler@Jugglers-Air ~ % osxphotos --help
/Users/Juggler/.local/share/uv/tools/osxphotos/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/Juggler/.local/bin/osxphotos", line 5, in <module>
    from osxphotos.__main__ import cli_main
  File "/Users/Juggler/.local/share/uv/tools/osxphotos/lib/python3.9/site-packages/osxphotos/__init__.py", line 17, in <module>
    from .iphoto import (
  File "/Users/Juggler/.local/share/uv/tools/osxphotos/lib/python3.9/site-packages/osxphotos/iphoto.py", line 64, in <module>
    from .photoinfo import PhotoInfo
  File "/Users/Juggler/.local/share/uv/tools/osxphotos/lib/python3.9/site-packages/osxphotos/photoinfo.py", line 56, in <module>
    from .bookmark import resolve_bookmark_path
  File "/Users/Juggler/.local/share/uv/tools/osxphotos/lib/python3.9/site-packages/osxphotos/bookmark.py", line 12, in <module>
    def resolve_bookmark_path(bookmark_data: bytes) -> pathlib.Path | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by RhetTbull** [comment]
The problem is python 3.9 which OSXPhotos no longer supports. I'm surprised uv used a version the project metadata states it doesn't support. Try this to see if it works:

`uv tool run --python 3.12 osxphotos `

If so you can uninstall it and reinstall with the `--python 3.12` option

**Comment by Juggler00** [comment]
Success... that did the trick. Thank you!

**Comment by RhetTbull** [comment]
Great! I'll update the README appropriately
