### ISSUE TITLE
Latest version 0.35.1 misses 'py' dependency 

### ISSUE THREAD

**Issue by garz75** [RhetTbull/osxphotos#234]
```
$ python3 -m pip install --upgrade osxphotos
<.....>
Successfully installed osxphotos-0.35.1 wurlitzer-2.0.1
$ osxphotos help
Traceback (most recent call last):
  File "/usr/local/bin/osxphotos", line 5, in <module>
    from osxphotos.__main__ import cli
  File "/usr/local/lib/python3.8/site-packages/osxphotos/__init__.py", line 4, in <module>
    from .photoinfo import PhotoInfo
  File "/usr/local/lib/python3.8/site-packages/osxphotos/photoinfo/__init__.py", line 8, in <module>
    from ._photoinfo_export import ExportResults
  File "/usr/local/lib/python3.8/site-packages/osxphotos/photoinfo/_photoinfo_export.py", line 34, in <module>
    from ..exiftool import ExifTool
  File "/usr/local/lib/python3.8/site-packages/osxphotos/exiftool.py", line 16, in <module>
    from .utils import _debug
  File "/usr/local/lib/python3.8/site-packages/osxphotos/utils.py", line 23, in <module>
    from .fileutil import FileUtil
  File "/usr/local/lib/python3.8/site-packages/osxphotos/fileutil.py", line 11, in <module>
    from .imageconverter import ImageConverter
  File "/usr/local/lib/python3.8/site-packages/osxphotos/imageconverter.py", line 14, in <module>
    from py import path
ModuleNotFoundError: No module named 'py'
```

workaround : 
```
$ python3 -m pip install py
```

**Comment by RhetTbull** [comment]
@garz75 Thanks! I've fixed this in v0.35.2.  That was an interesting bug...I don't actually use the "py" module so I wondered 
1) how it got there and 
2) how it made it through both my test suite and the GitHub Actions automated tests that run when I do a new release.  

The answer to the first question is I've been using a new [PyLance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) extension for my editor which includes an "auto import" feature...it tries to guess which imports you need as you type and automatically add them.  I didn't know it was doing this and have turned that off...a terrible feature in my opinion.  

The answer to the second question is that [pytest](https://docs.pytest.org/en/stable/), which I use for testing, uses this module and hence it was always installed when running tests!
