### ISSUE TITLE
Crash in handling exiftool as export template

### ISSUE THREAD

**Issue by narensankar0529** [RhetTbull/osxphotos#311]
Getting this crash - 

Using last opened Photos library: /Volumes/PhotoSync/nsankar/Photos Library.photoslibrary
Exporting 35817 photos to /Volumes/PhotoSync/FotosOutput/Fotos.nsankar...
Traceback (most recent call last):
  File "/usr/local/bin/osxphotos", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/osxphotos/__main__.py", line 2126, in export
    export_results = export_photo(
  File "/usr/local/lib/python3.9/site-packages/osxphotos/__main__.py", line 2789, in export_photo
    filenames = get_filenames_from_template(photo, filename_template, original_name)
  File "/usr/local/lib/python3.9/site-packages/osxphotos/__main__.py", line 3049, in get_filenames_from_template
    filenames, unmatched = photo.render_template(
  File "/usr/local/lib/python3.9/site-packages/osxphotos/photoinfo/photoinfo.py", line 858, in render_template
    return template.render(
  File "/usr/local/lib/python3.9/site-packages/osxphotos/phototemplate.py", line 318, in render
    rendered_strings = self._render_exiftool_template(
  File "/usr/local/lib/python3.9/site-packages/osxphotos/phototemplate.py", line 520, in _render_exiftool_template
    exif = ExifTool(self.photo.path)
  File "/usr/local/lib/python3.9/site-packages/osxphotos/exiftool.py", line 155, in __init__
    self._exiftoolproc = _ExifToolProc(exiftool=exiftool)
  File "/usr/local/lib/python3.9/site-packages/osxphotos/exiftool.py", line 59, in __init__
    self._exiftool = exiftool or get_exiftool_path()
  File "/usr/local/lib/python3.9/site-packages/osxphotos/exiftool.py", line 29, in get_exiftool_path
    raise FileNotFoundError(
FileNotFoundError: Could not find exiftool. Please download and install from https://exiftool.org/
Exception ignored in: <function _ExifToolProc.__del__ at 0x11015bd30>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/osxphotos/exiftool.py", line 129, in __del__
  File "/usr/local/lib/python3.9/site-packages/osxphotos/exiftool.py", line 109, in _stop_proc
AttributeError: '_ExifToolProc' object has no attribute '_process_running'

**Comment by narensankar0529** [comment]
/usr/local/bin/osxphotos export --update --cleanup --not-hidden --not-shared --not-screenshot \
  --skip-original-if-edited --skip-raw --skip-live --skip-bursts \
  --touch-file \
  --exiftool-path "/usr/local/bin/exiftool" \
  --sidecar xmp \
  --sidecar-drop-ext \
  --sidecar exiftool \
  --keyword-template "{label_normalized}" \
  --keyword-template "{searchinfo.venue_type}" \
  --keyword-template "{searchinfo.season}" \
  --keyword-template "{searchinfo.holiday}" \
  --keyword-template "{searchinfo.activity}" \
  --keyword-template "{searchinfo.venue}" \
  --keyword-template "{searchinfo.venue_type}" \
  --directory '{photo_or_video}/{created.year}/{created.month}/{created.dd}' --filename "{exiftool:EXIF:Make}_{media_type}_{created.yy}{created.mm}{created.dd}_{modified.sec}" \
  --report $logFileName.csv \
  ${libraryExportDir} >> $logFileName 2>&1

**Comment by RhetTbull** [comment]
exiftool_path isn't being passed to PhotoInfo.render -- working on a fix now

**Comment by RhetTbull** [comment]
I think this is the same issue you had with #313.  Fix pushed in [v0.39.1](https://github.com/RhetTbull/osxphotos/releases/tag/v0.39.1) 

I added a test for this scenario -- I wasn't passing the custom exiftool-path to the template code.
