### ISSUE TITLE
When installed with pipx, latest version fails to execute because of missing 'more_itertools' module

### ISSUE THREAD

**Issue by garz75** [RhetTbull/osxphotos#466]
after pipx upgrade / (or pipx uninstall osxphotos / pipx instal osxphotos) : 

```
$ osxphotos --version
Traceback (most recent call last):
  File "/Users/fgarzon/.local/bin/osxphotos", line 5, in <module>
    from osxphotos.__main__ import cli
  File "/Users/fgarzon/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/osxphotos/__main__.py", line 3, in <module>
    from .cli import cli
  File "/Users/fgarzon/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/osxphotos/cli.py", line 55, in <module>
    from .photosalbum import PhotosAlbum
  File "/Users/fgarzon/.local/pipx/venvs/osxphotos/lib/python3.9/site-packages/osxphotos/photosalbum.py", line 6, in <module>
    from more_itertools import chunked
ModuleNotFoundError: No module named 'more_itertools'
```

This module has been added recently (83892e09)...

**Comment by RhetTbull** [comment]
Sorry about that--it should be fixed now.

**Comment by RhetTbull** [comment]
I just tried pipx and it works with [v0.42.34](https://github.com/RhetTbull/osxphotos/releases/tag/v0.42.34)
