### ISSUE TITLE
Errors on Monterey

### ISSUE THREAD

**Issue by narensankar0529** [RhetTbull/osxphotos#542]
Getting the following error running on Monterey -

osxphotos --version
Traceback (most recent call last):
  File "/opt/homebrew/bin/osxphotos", line 5, in <module>
    from osxphotos.__main__ import cli
  File "/opt/homebrew/lib/python3.9/site-packages/osxphotos/__init__.py", line 4, in <module>
    from .photoinfo import ExportResults, PhotoInfo
  File "/opt/homebrew/lib/python3.9/site-packages/osxphotos/photoinfo/__init__.py", line 8, in <module>
    from ._photoinfo_export import ExportResults
  File "/opt/homebrew/lib/python3.9/site-packages/osxphotos/photoinfo/_photoinfo_export.py", line 51, in <module>
    from ..photokit import (
  File "/opt/homebrew/lib/python3.9/site-packages/osxphotos/photokit.py", line 26, in <module>
    import CoreServices
  File "/opt/homebrew/lib/python3.9/site-packages/CoreServices/__init__.py", line 12, in <module>
    import FSEvents
  File "/opt/homebrew/lib/python3.9/site-packages/FSEvents/__init__.py", line 10, in <module>
    import FSEvents._callbacks
RuntimeError: Wrong version of PyObjC C API (got 22, expected 21)

**Comment by RhetTbull** [comment]
How did you install osxphotos?  Looks like you installed it with `pip install osxphotos` with the homebrew version of python.  If so, try this: `python3 -m pip install pyobjc==8.1` and see if you still get the same errors.

**Comment by narensankar0529** [comment]
So I normally update osxphotos as follows - /opt/homebrew/bin/pip3 -q install -U osxphotos

For some reason this had left a /opt/homebrew/lib/python3.9/site-packages/~sxphotos and this was causing the issue. Once I deleted that directory osxphotos started to work again correctly.

Do I need to add the pyobjc==8.1 to the command line for updates?

**Comment by RhetTbull** [comment]
> Do I need to add the pyobjc==8.1 to the command line for updates?

Not if it's now working that since you removed the old package.  It was a guess since I'm not on M1 and trying to figure out what might be causing the error.  pyobjc has been updated for M1 but I don't know if the update is required.

**Comment by narensankar0529** [comment]
Ok. Got it. Thanks
