### ISSUE TITLE
Database fails to load with Ventura

### ISSUE THREAD

**Issue by davidbernat** [RhetTbull/osxphotos#810]
Chip: Apple M1
macOS: 13.0 (22A380)
Photos: Version 8.0 (511.0.180)
IDE: IntelliJ IDEA 2022.2.3

```
import osxphotos
photo_library_path = "<path>"
photosdb = osxphotos.PhotosDB(dbfile=photo_library_path)
```

```
Connected to pydev debugger (build 222.4345.14)
2022-10-31 18:13:14,556 - WARNING - photosdb.py - 112 - WARNING: This module has only been tested with macOS versions [10.12, 10.13, 10.14, 10.15, 10.16, 11.0, 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 12.0, 12.1, 12.2, 12.3]: you have Darwin, OS version: 13.0
2022-10-31 18:13:14,683 - WARNING - photosdb_utils.py - 96 - Unknown model version: 16311
Traceback (most recent call last):
  File "/Users/REMOVED/Library/Application Support/JetBrains/IdeaIC2022.2/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/REMOVED/Library/Application Support/JetBrains/IdeaIC2022.2/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/REMOVED/github/REMOVED/utilities.py", line 37, in <module>
    photosdb = osxphotos.PhotosDB(dbfile=photo_library_path)
  File "/Users/REMOVED/.pyenv/versions/3.10.2/lib/python3.10/site-packages/osxphotos/photosdb/photosdb.py", line 353, in __init__
    self._process_database5()
  File "/Users/REMOVED/.pyenv/versions/3.10.2/lib/python3.10/site-packages/osxphotos/photosdb/photosdb.py", line 1720, in _process_database5
    c.execute(
sqlite3.OperationalError: no such table: Z_27ASSETS
python-BaseException
```

**Comment by RhetTbull** [comment]
I don’t have access to Ventura but I know how to fix this. It would be helpful to know what else has changed in the database though.  Could you run the following and post the output here?

`sqlite3 ~/Pictures/Photos\ Library.photoslibrary/database/Photos.sqlite ".schema" > ventura_photos_schema.txt`

I’ve tested osxphotos with the dev beta of Ventura and it works but looks like at least one table has changed names.

**Comment by davidbernat** [comment]
Got it. Here you go. 
[ventura_photos_schema.txt](https://github.com/RhetTbull/osxphotos/files/9906207/ventura_photos_schema.txt)

**Comment by RhetTbull** [comment]
Thanks!

**Comment by RhetTbull** [comment]
The schema you sent is consistent with the 13.0 dev preview version I'd previously tested with [minor differences](https://github.com/RhetTbull/osxphotos/wiki/Photos-8---Ventura-13.0-dev-preview-to-Ventura-13.0.0-release-diff) that shouldn't have caused this error. Please ensure you're running the most recent version of osxphotos (0.51.8) and try again.

**Comment by dmd** [comment]
I'm using Ventura and do not have this issue.

**Comment by davidbernat** [comment]
I am checking to see whether an out of date version of osxphotos lead to
the error. My version did need to be updated. I have not yet had time to
check whether that solves the problem.

**Comment by eduardkieser** [comment]
I think I have a related issue.
```
import osxphotos
photosdb = osxphotos.PhotosDB()
photos = photosdb.photos()
path_list = [p.path for p in photos if p.path is not None]
print(f"{len(path_list)} files found")
```
produces
```
2022-11-19 15:24:58,587 - WARNING - photosdb.py - 119 - WARNING: This module has only been tested with macOS versions [10.12, 10.13, 10.14, 10.15, 10.16, 11.0, 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 12.0, 12.1, 12.2, 12.3, 12.4, 12.5, 12.6]: you have Darwin, OS version: 13.0
1161 files found
```
But I have more than 13,000 photos in my library, and this used to work as expected before updating macOS. Also, is there a better way to get the file list of all my photos on mac?
14" M1 Mac, 
Ventura 13.0.1, 
Photos Version 8.0 (511.0.180), 
osxmetadata==1.2.2
osxphotos==0.54.3 (updated with pip on 19 Nov)

**Comment by RhetTbull** [comment]
The path will be None if the original photo is not available on the disk. Do you have `Optimize Mac Storage` checked in Photos Preferences?

**Comment by eduardkieser** [comment]
That was indeed the case, I set it to download and it seems to be synching. Thanks for the heads up.
