### ISSUE TITLE
ModuleNotFoundError: No module named 'Foundation._context.Foundation'

### ISSUE THREAD

**Issue by dmd** [RhetTbull/osxphotos#811]
I have two MacOS Ventura machines. On one of them osxphotos works just fine. On the other:

```
$ sw_vers
ProductName:		macOS
ProductVersion:		13.0
BuildVersion:		22A380

$ osxphotos --version
Traceback (most recent call last):
  File "cli.py", line 16, in <module>
  File "/Users/rhet/anaconda3/envs/osxphotos/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "osxphotos/__init__.py", line 4, in <module>
  File "/Users/rhet/anaconda3/envs/osxphotos/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "osxphotos/photoinfo/__init__.py", line 8, in <module>
  File "/Users/rhet/anaconda3/envs/osxphotos/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "osxphotos/photoinfo/_photoinfo_export.py", line 34, in <module>
  File "/Users/rhet/anaconda3/envs/osxphotos/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "osxphotos/exiftool.py", line 16, in <module>
  File "/Users/rhet/anaconda3/envs/osxphotos/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "osxphotos/utils.py", line 19, in <module>
ModuleNotFoundError: No module named 'Foundation._context.Foundation'; 'Foundation._context' is not a package
[75789] Failed to execute script cli
```

**Comment by dmd** [comment]
Whoops, I had a very old version in $HOME/bin shadowing the new install.
