### ISSUE TITLE
if --tmpdir does not exist, osxphotos crashes with error

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#969]
This is a weird error that happens if osxphotos export --tmpdir TMPDIR does not exist:

```
osxphotos version: 0.56.7
Error: Error binding parameter 14: type 'FileNotFoundError' is not supported
Traceback (most recent call last):
  File "/Users/rhet/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/osxphotos/crash_reporter.py", line 36, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rhet/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/osxphotos/cli/export.py", line 1673, in export
    report_writer.write(export_results)
  File "/Users/rhet/.local/pipx/venvs/osxphotos/lib/python3.11/site-packages/osxphotos/cli/report_writer.py", line 195, in write
    cursor.execute(
sqlite3.ProgrammingError: Error binding parameter 14: type 'FileNotFoundError' is not supported
```

**Comment by RhetTbull** [comment]
Could not replicate. `--tmpdir` is a click.Path and correctly exits if it doesn't exist:

```
osxphotos export ~/Desktop/export -V --tmpdir /foo
Usage: python -m osxphotos export [OPTIONS] [PHOTOS_LIBRARY]... DEST
Try 'python -m osxphotos export -h' for help.

Error: Invalid value for '--tmpdir': Directory '/foo' does not exist.
```
